// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyacitwbkrhousvmeuaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5YWNpdHdia3Job3Vzdm1ldWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNjIzOTQsImV4cCI6MjA1OTkzODM5NH0.WXs4uJjuzCidtx0GrSsvk6gyPI8A-xwjotsD98Ie3Y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);